### ISSUE TITLE
Auction info prints StringParser

### ISSUE THREAD

**Issue by Pheotis** [Alchemi1963/AuctionStorm#2]
### Description
in v`2.0.4`, the command `/as info` prints a string after `AuctionStorm.Auction.Info.Time` on `debian 10` running `paper-195` (1.16.3)

### Example:
```yaml
=====Current Auction=====
Item: example
Amount: 1
Starting Bid: 1 credits
Time Remaining: 56 secondsme.alchemi.as.objects.placeholder.StringParser@36f42d50
```

### Workarounds
This issue appears to be minor as it has no noticeable impact on the plugin's features.
As a temporary, band-aid, solution, the time string of messages.yml can be appended with a `/n` and the print can be nullified with regex (`/me.alchemi.as.objects.placeholder.StringParser@......../`).
